### PR TITLE
Update PureScript to v0.13.0

### PR DESCRIPTION
**Pull request by garyb**
Release notes: https://github.com/purescript/purescript/releases/tag/v0.13.0

### CODE REVIEW

**Comment by srghma** [comment]
@garyb could you merge please? )

**Comment by kRITZCREEK** [comment]
@srghma Don't rush people like that please, it's rude.

**Comment by srghma** [comment]
tnx guys!

**Comment by garyb** [comment]
Just for future reference, I was leaving this PR open/unmerged as only @shinnn, the author, has the ability to make the release on `npm`.

**Comment by bosyi** [comment]
Yes, because now this PR merged but no new version to npm deployed.

**Comment by thomashoneyman** [comment]
😬 I see. Sorry about that, @shinnn & @garyb.

**Comment by shinnn** [comment]
I just published `0.13.0` to npm. I didn't have enough spare time recently.

@thomashoneyman No need to be sorry. Thanks for the review.

**Pull request merged**
